language: bash
services: docker
before_install: 
    - cd ecommerce
    - echo "We are in the Docker folder!"
script:
    - docker-compose build
before_deploy:
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
    provider: script
    script:
        docker push markstech/ecommerce;
        docker push markstech/ecommerce-db;
    on: 
        branch: master
notifications: false
