version: '3.4'
services:
    db:
        image: markstech/ecommerce
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: D0ck3r@2020 
            MYSQL_USER: docker
            MYSQL_PASSWORD: D0ck3r@2020
            MYSQL_DATABASE: ecommerce
    ecommerce:
networks:
    ecommerce-network:
        driver: bridge
