version: '3.4'
services:
    db:
        image: markstech/ecommerce-db
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: D0ck3r@2020 
            MYSQL_USER: docker
            MYSQL_PASSWORD: D0ck3r@2020
            MYSQL_DATABASE: ecommerce
        ports: 
            - "3308:3308"
        networks:
            - ecommerce-network 
    ecommerce:
        image: markstech/ecommerce-back
        restart: always
        build: ./ecommerce
        working_dir: /ecommerce
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes: 
            - ./ecommerce: /ecommerce
            - ~/.m2
        ports: 
            - "80880:8080"
        command: mvn clean spring-boot:run
        links: 
            - db
        depends-on:
            - db
        networks:
            - ecommerce-network 
networks:
    ecommerce-network:
        driver: bridge
